platform :ios, '7.0'

pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'AFNetworkActivityLogger'
pod 'ReactiveCocoa'
pod 'SDWebImage'
pod 'JGProgressHUD'
pod 'MJRefresh'
pod 'UITableView+FDTemplateLayoutCell'
pod 'Masonry'